### ISSUE TITLE
.github/bots.yml as alternative location for placement

### ISSUE THREAD

**Issue by chrisparnin** [monperrus/bots.yml#1]
I would propose in addition to the root of the repo, that people be allowed to place this file in `.github/bots.yml`. This folder is typically used to manage a repo's community guidelines, LICENSE, etc. Seems like a reasonable location for people not wanting to clutter the root directory.

https://help.github.com/en/articles/setting-up-your-project-for-healthy-contributions

**Comment by monperrus** [comment]
fixed by https://github.com/monperrus/bots.yml/commit/5cb32a745442c88b4844b7e3481827d5b0a1db8b#diff-04c6e90faac2675aa89e2176d2eec7d8
